# The URL the site will be built for
base_url = "https://adityadeshlahre.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

title = "Hello there"
description = "I’m  ```Aditya Deshlahre```  — I tinker with Linux, open source, AI, and code in TypeScript & Go. I focus on backend work, infra, deployments, and designing reliable systems."

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

default_language = "en"

generate_robots_txt = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

highlight_theme = "OneHalfLight"

[extra]

mode = "toggle"

useCDN = false

favicon = "https://adityadeshlahre.github.io/icon/favicon.png"

copyright = "A-D"

katex_enable = true

og_title = "Hello there"

og_description = "I tinker with Linux, open source, AI, TypeScript, Go — backend, infra & systems."

og_image = "https://adityadeshlahre.github.io/icon/ogimage.png"

og_logo = "https://adityadeshlahre.github.io/icon/oglogo.png"

site_name = "Aditya"

[extra.translations]
languages = [{name = "en", url = "/"}]

[[extra.translations.en]]
show_more = "Read more ⟶"
previous_page = "← Previous"
next_page = "Next →"
posted_on = "on "
posted_by = "Published by"
read_time = "minute read"
all_tags = "All tags"
menus = [
    { name = "Home", url = "/", weight = 2 },
    { name = "Projects", url = "/projects", weight = 4 },
    { name = "Resumse", url = "https://drive.google.com/file/d/1OVdi_4yPk0xKglRnTQKG6sLKo9Zq7QRb/view", weight = 3},
    { name = "Work", url = "https://dub.sh/proved", weight = 2 },
    { name = "About", url = "/about", weight = 3 },
    { name = "Blogs", url = "/posts", weight = 2 },
]

# config social icon info in the footer
[[extra.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/adityadeshlahre/"

[[extra.social]]
icon = "twitter"
name = "Twitter"
url = "https://x.aditya.ovh/"

[[extra.social]]
icon = "linkedin"
name = "LinkedIn"
url = "https://l.aditya.ovh/"

[[extra.social]]
icon = "phone-call"
name = "CalDotCom"
url = "https://cal.com/adityadeshlahre/"

[[extra.social]]
icon = "mail"
name = "Email"
url = "mailto:wymaditya@gmail.com"

[[extra.meta]]
property = "og:title"
content = "Hello there"

[[extra.meta]]
property = "og:description"
content = "I tinker with Linux, open source, AI, TypeScript, Go — backend, infra, deployments & systems."

[[extra.meta]]
property = "og:site_name"
content = "Aditya"

[[extra.meta]]
property = "og:image"
content = "https://adityadeshlahre.github.io/icon/ogimage.png"

[[extra.meta]]
property = "og:type"
content = "website"

[[extra.meta]]
property = "og:url"
content = "https://adityadeshlahre.github.io"

[[extra.meta]]
name = "twitter:card"
content = "summary_large_image"

[[extra.meta]]
name = "twitter:title"
content = "Hello there"

[[extra.meta]]
name = "twitter:description"
content = "I tinker with Linux, open source, AI, TypeScript, Go — backend, infra & systems."

[[extra.meta]]
name = "twitter:image"
content = "https://adityadeshlahre.github.io/icon/ogimage.png"

[[extra.meta]]
name = "twitter:creator"
content = "@adityadeshlahre" 
